server:
  port: 8082
  servlet:
    context-path: /vkr

postgresql:
  host: 127.0.0.1
  port: 5432
  database: postgres
  username: postgres
  password: postgres

spring:
  application:
    name: coldstart_service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://${postgresql.host}:${postgresql.port}/${postgresql.database}
    username: ${postgresql.username}
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    platform: postgres
    initialization-mode: always

vkr:
  cold-start-user-answers-output-file: "cold_start_data.csv"
  cold-start-data-path: "/data"
  cold-start-events-interval: 30
  cold-start-events-count-at-page: 3
  cold-start-events-count-page: 10
  cold-start-questions:
    - 'Пожалуйста, выберете одно из понравившихся мероприятий'
    - 'Что вам больше нравится?'